
  name: PushPreview

  on:
    pull_request_target:
      types:
        - labeled
  
  jobs:
    preview:
      runs-on: ubuntu-latest
      if: github.event.label.name == 'preview'
      steps:
        - uses: actions/checkout@v3
        - name: Comment
          run: |
            gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body "⚙️ Hang tight! PushPreview is currently building your preview. We'll share the URL as soon as it's ready."
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
        - uses: actions/setup-python@v2
          with:
            python-version: "3.10"
  
        - name: Set BASE_URL
          run: echo "BASE_URL=/github/${{ github.repository }}/${{ github.event.number }}/" >> $GITHUB_ENV
  
        - name: Build site
          run: |
            cd docs
            pip install -r requirements.txt
            make dirhtml

        - name: Generate preview
          uses: PushLabsHQ/pushpreview-action@1.0.6
          with:
            source-directory: ./docs/_build/html
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pushpreview-token: ${{ secrets.PUSHPREVIEW_TOKEN }}